name: pypeit
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pyyaml>=5.1
  - requests>=2.23
  - packaging>=19.0
  - numpy>=1.18
  - scipy>=1.4
  - scikit-learn>=0.20
  - astropy>=4.0
  - setuptools>=46.4
  - matplotlib>=3.1
  - configobj>=5.0.6
  - ipython>=7.2
  - extension-helpers>=0.1
  - ginga>=3.0
  - qtpy>=1.9
  - pytest>=3.0.7
  - bottleneck>=1.3
  - pip
  - linetools>=0.3dev2231
